### ISSUE TITLE
Wireframe for generic page structure

### ISSUE THREAD

**Issue by cazinc** [CDLUC3/dmsp_frontend_prototype#130]
Produce a wireframe for a generic page template, with (for example) elements for straight text, etc.

**Comment by fraserclark** [comment]
@PaulaReeves @andrewebdev @briri @bofstein @jupiter007 @cazinc 

We ended up making a bigger change here, as we took a step back and trying to think about the whole application in a mobile way along with the generic pages we started to talk through and figure out some of the issues we might come across.


So we have created a video trying to explain the reasoning 
https://www.loom.com/share/213b568650244cec84bd82e3ebb04e00


**Generic Page Start** 
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2341-317&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

**Generic Page Start Mobile**
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2344-1833&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

**Generic Page**
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2293-1385&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

**Generic Page Mobile**
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2293-1412&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1


**Also mentioned - Profile page**

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2344-1901&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2344%3A1901&show-proto-sidebar=1


**Example of page** with "right sidebar trigger" eg "best practises by DMP button" - ignore the literal content on this page more the mechanism of how a button could trigger a right side bar

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2309-1720&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2309%3A1720&show-proto-sidebar=1


**Plan edit**
This is the example of mobile first version of the plan edit - and the potential table of contents 

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2329-1663&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=177%3A504&starting-point-node-id=177%3A642&show-proto-sidebar=1

**Comment by jupiter007** [comment]
Thanks so much for the video Fraser. It looks great.

I added some comments on the video, but I thought I should share my comments in the email as well.

I like the list-style view in place of the left sidebar menu, but I’m concerned that users will no longer have a good overview of topics available to them unless they scroll down the page. On the  www.gov.uk<https://www.gov.uk/> site, links to the same list items are included in the main menu. I think this helps users to see all the content in one place, and to help them navigate more easily from one page to another. We could also consider using the table of contents example that you shared as well.

I really like the use of breadcrumbs on the www.gov.uk<http://www.gov.uk> site to help users orient themselves. Also, I like how they shorten the breadcrumb for mobile view.

Instead of showing the best practices links in the right sidebar slider, could we consider an expanding accordion?

I like that you added a header to the right sidebar “Save & Publish” data on mobile. Should we use that save header when the data is in the right sidebar to make the content more cohesive?

On the www.gov.uk<http://www.gov.uk> site, I really liked that the table of contents pages gave users the option to click on “prev” and “next” in the body of each page.



Juliet Shin
University of California, Office of the President
1100 Broadway, 10th Flr, 10009B, Oakland, CA 94607
***@***.******@***.***>



From: Fraser Clark ***@***.***>
Date: Friday, October 4, 2024 at 6:23 AM
To: CDLUC3/dmsp_frontend_prototype ***@***.***>
Cc: Juliet Shin ***@***.***>, Mention ***@***.***>
Subject: Re: [CDLUC3/dmsp_frontend_prototype] Wireframe for generic page structure (Issue #130)

CAUTION: EXTERNAL EMAIL

@PaulaReeves<https://github.com/PaulaReeves> @andrewebdev<https://github.com/andrewebdev> @briri<https://github.com/briri> @bofstein<https://github.com/bofstein> @jupiter007<https://github.com/jupiter007> @cazinc<https://github.com/cazinc>

We ended up making a bigger change here, as we took a step back and trying to think about the whole application in a mobile way along with the generic pages we started to talk through and figure out some of the issues we might come across.

So we have created a video trying to explain the reasoning
https://www.loom.com/share/213b568650244cec84bd82e3ebb04e00

Generic Page Start
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2341-317&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

Generic Page Start Mobile
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2344-1833&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

Generic Page
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2293-1385&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

Generic Page Mobile
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2293-1412&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

Also mentioned - Profile page

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2344-1901&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2344%3A1901&show-proto-sidebar=1

Example of page with "right sidebar trigger" eg "best practises by DMP button" - ignore the literal content on this page more the mechanism of how a button could trigger a right side bar

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2309-1720&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2309%3A1720&show-proto-sidebar=1

Plan edit
This is the example of mobile first version of the plan edit - and the potential table of contents

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2329-1663&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=177%3A504&starting-point-node-id=177%3A642&show-proto-sidebar=1

**Comment by bofstein** [comment]
Thanks for these options Fraser.  I agree the list-to-detail view would be good to keep.  

I personally like the Related Actions view while still having the main list previously:
![Image](https://github.com/user-attachments/assets/3a363a06-3b0a-4503-9884-8234f804ea39)

Do you think that's feasible/reasonable to have on those pages?  And keeping the Gateway page, as we're not using left-nav?  We don't have a huge number of pages, so it's the kind of thing I imagine we manually build, but could update over time if we see how people use it or what they have trouble finding.  E.g. adding a link to their Dashboard if that's what people usually go to, rather than just treating it like a nav that always shows every page in that section.

**Comment by bofstein** [comment]
I'm not clear how the "related links" idea works on Mobile - the mobile link seems to show a table of contents at the top more like navigation.  I thought you had shown in the meeting a related links section at the bottom.  The idea is to make it unobtrusive, so if they didn't find what they wanted at the end they might see something in a related link

**Comment by cazinc** [comment]
Hi @bofstein, I think it may just be that the mobile link points to one mobile screen when there are many, and this link happens to not show the Related Links section. Try https://www.figma.com/design/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2470-871&m=dev instead. Let us know if that helps.

**Comment by bofstein** [comment]
We seemed to all agree on this Related Links/Actions version in meeting so closing.  No left nav, yes to main page link tree.
