### ISSUE TITLE
Decide how to configure maintainer

### ISSUE THREAD

**Issue by cazinc** [CDLUC3/dmsp_frontend_prototype#47]
Hi - this is really a question more than anything, just a way to center the discussion. 

There is the concept of a **maintainer** for a template. The template picker (#31) shows this on each card on the grid of suggested templates. In previous discussions it was agreed this would be a person rather than an org (except if it's "DMPTool") and that there would be a total of up to 3 individual maintainers shown somehow. 

As @fraserclark and I have been working through the template builder wireframes, we came up with some questions about how or if a maintainer is selected during the process, whether there should be some sort of connection between maintainer(s) and creator/collaborator(s), etc. I think we're still a bit unclear on how this would all work from both the template builder and plan builder standpoints, so we've come up with some clarifying questions and comments, below. 

- What is the value to the user of showing an individual maintainer? We think it's just to get across that a template "is actively maintained"? 
- Can or should the maintainer be the template creator, or a designated collaborator? Or is the maintainer some other role? Might there be an org wide "maintainer person" across all their templates?
- If a maintainer is selected during template creation, or even if we force it to the template originator, what if that person leaves? Or what if someone who isn't the creator isn't the "right person to show as maintainer" (e.g. intern creates templates, but they aren't the best contact). A common/shared/org maintainer might be better if so. 
- Is there any specific thinking about why we'd show 3 maintainers, e.g. to demonstrate lots of active maintainers, or to show who last edited? 
- It's been acknowledged that a named maintainer might not wish to get emails or other contacts about a template, or at least that the thought that this could happen might be a blocker to creation, or possibly lead to "can I hide my name somehow" queries. 

Our feeling is that some other way of showing a template "is maintained" might be safer and more straightforward given the above, what are your thoughts? 

My original thinking when creating the picker wireframe was that an indication of how recently something was updated might be best. For example "Updated 3 weeks ago". This too though could be a bit tricky, as we're assuming that many templates won't be actively maintained, and even that in some cases that's fine. Maybe a template is created and rarely requires active amends during it's life? 

We thought about various other criteria to use here, like highlighting templates updated in the last x weeks, but per the last paragraph this may not be valid if something is "old but still valid". 

So we're a bit stuck as to what would be best for user here, and wondered if perhaps some other criteria could be useful, like number of uses of the template? This could show that something is actively being used. 

Sorry, bit longwinded, but wanted to get all our various thoughts down. @fraserclark anything to add?

**Comment by briri** [comment]
My understanding was that the use case was to give people credit for doing the work of creating/editing the template. I think that the card should be simple and just show the last few people who edited it. I think that in most cases this will be a single person, so adding some sort of hierarchy and a place to designate the maintainer is unnecessary. I'm interested to hear other opinions.

**Comment by mariapraetzellis** [comment]
Here are my thoughts on "Maintainer" for discussion with @briri and @jupiter007 

What is the value to the user of showing an individual maintainer? We think it's just to get across that a template "is actively maintained"?
**- The goal is to credit the volunteers who maintain the templates for their work. We want to encourage people to help keep templates updated, so this is a way to acknowledge their work.** 

Can or should the maintainer be the template creator, or a designated collaborator? Or is the maintainer some other role? Might there be an org wide "maintainer person" across all their templates?
**- We will go with "Last updated: DATE by USER NAME"** 

If a maintainer is selected during template creation, or even if we force it to the template originator, what if that person leaves? Or what if someone who isn't the creator isn't the "right person to show as maintainer" (e.g. intern creates templates, but they aren't the best contact). A common/shared/org maintainer might be better if so.
- **Going with "Last updated...." rather than maintainer will make this easier to manage, e.g., interns, people moving organizations..**.

Is there any specific thinking about why we'd show 3 maintainers, e.g. to demonstrate lots of active maintainers, or to show who last edited?
**- We will show who last edited rather than several maintainers.** 

It's been acknowledged that a named maintainer might not wish to get emails or other contacts about a template, or at least that the thought that this could happen might be a blocker to creation, or possibly lead to "can I hide my name somehow" queries.
**- Yes, I think the option to "hide my name" would be useful. Perhaps this could be a setting on the template builder**

**Comment by cazinc** [comment]
This is all super helpful, thanks @mariapraetzellis. We'll action this in the template picker wireframes as we integrate them into the overall interactive wireframes for creating a template.
