### ISSUE TITLE
Create functional ReMirror editor

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#74]
From https://github.com/CDLUC3/dmsp_frontend_prototype/issues/6, we are going to go with ReMirror, unless we find it cannot work for us and need to change.  First step is to get a full demo working with the features we need.

**Comment by andrewebdev** [comment]
@briri & @jupiter007 ; Do we know yet how we are going to store annotations in the database/backend? I'm assuming this is not yet well planned out because we might want to connect those comments with specific fields and users, some of which are not yet finalized.

**Comment by jupiter007** [comment]
That's a good question @andrewebdev. We haven't put any thought into where we're going to store annotations, and how we will store it. I would think we would need the following fields:

commentId
planId
userId
content
position
timestamp
parent comment id

Also, if we're expecting real-time editing, would mysql work for that? We would probably need to use a websocket, like what would be used for a chat?

**Comment by andrewebdev** [comment]
I normally use a message queue like RabbitMQ, and then I have a backend task that later sync the messages into the DB.

That said, I'm starting to wonder if comments should be done at a later phase when other technologies are more fixed in place? Might be worth a 5 minute chat tomorrow?

**Comment by briri** [comment]
Yes, we can discuss tomorrow in the meeting. I hadn't given it a lot of thought since we met in Edinburgh.

Originally I was think we could use a table that uses a polymorphic association pattern. I think though that it will depend a lot on how the comments are referenced within ReMirror. How does it markup the editor's HTML to embed or link the comment to a particular part of the text?

At minimum we will want this for the MVP for answers to questions on the DMP editing screens. The polymorphic pattern will still work with that and allow us to grow. So maybe something like:
- textFieldId (the id of the thing the comment is associated with `answerId` in our initial case)
- textFieldType (to start, we will just have `Answer` here)
- commentorId (user's id)
- comment
- any markup ReMirror needs to contextualize the comment within the answer

**Comment by andrewebdev** [comment]
In the richtext fields, remirror saves the "marks" for annotations in a separate JSON structure. But we can serialize this into the HTML when saving it. So In theory we can save it in the HTML. Since it's a separate JSON structure, we could also save this to the database separately. (hopefully I understood your question correctly ;) )

**Comment by briri** [comment]
Ahh ok. If it can be easily serialized/deserialized from the HTML then maybe the most efficient thing to do would be to store it inline with the text. We could then just make sure we strip it out when needed like when generating a PDF export.

**Comment by briri** [comment]
@bofstein we need to define what is necessary for the MVP to support commenting. We are finding that commenting can get very complicated quickly

**Comment by bofstein** [comment]
@briri Ok I will try to put some notes in by end of week, but as a quick response I think it can be minimal.  E.g. at a minimum, I think we could have just plain text comments, who the comment is from, and a point within text where that comment goes, more like a footnote. (if that's super hard, maybe we could even just associate a comment with a whole question, but it would be a lot better to have it inline).  Other things like highlighting text (as opposed to inserting at one point), having overlapping highlights, rich text in comments, etc, I think can be nice to haves.

**Comment by briri** [comment]
Adding comments to the field itself for now.

**Comment by briri** [comment]
@andrewebdev here is how TinyMCE is storing font sizes and colors chosen by the user. (Not suggesting we need to do it the same with reMirror, this is just for reference):
```
<p>One <strong>fish</strong> two <em>fish </em><span style="color: #e03e2d;">red <span style="color: #000000;">fish <span style="color: #3598db;">blue fish.</span></span></span></p>
<p><span style="font-size: 16pt;">Bigger size</span></p>
<p><span style="font-size: 8pt;">smaller size</span>&nbsp;</p>
```

@bofstein I ran some queries against the current DMPTool production system. Over the past 2 1/2 years (since Jan. 1, 2022) we have had:
- Out of 228,357 DMP answers
  - 600 that have a specific color specified
  - 1,159 that have a font size specification
- Out of 12,238 Template questions
  - 46 that have a specific color specified
  - 54 that have a font size specification

Of those, it looks like the majority are artifacts from copy/paste from other systems like MS Word. I base that assumption on the fact that they have a lot of HTML markup including `line-height`, colors as RGB values, etc.

**Comment by andrewebdev** [comment]
@briri That's some interesting stats. SO more answers use the font colours and size, and not that many in the templates. Interesting observation that it may be due to copy/paste from word/other.

What do you guys think we should take from this going forward? I feel like I'm not well-placed to make this decision, but if this is indeed the case, then it feels like we can remove these options from the editor without affecting users much?

**Comment by jupiter007** [comment]
Ok thanks for the update @andrewebdev

**Comment by andrewebdev** [comment]
@jupiter007 I just did a rebased my editor branch on `development` and I'm getting the following error:
```
 ⨯ ./components/TypeAheadWithOther/index.tsx:14:1
Module not found: Can't resolve './typeaheadWithOther.module.scss'
  12 | import Spinner from '@/components/Spinner';
  13 | import classNames from 'classnames';
> 14 | import styles from './typeaheadWithOther.module.scss';
     | ^
  15 | import logECS from '@/utils/clientLogger';
  16 |
  17 | type TypeAheadInputProps = {

https://nextjs.org/docs/messages/module-not-found
```
Is everything committed to that branch or are there changes pending?

**Comment by jupiter007** [comment]
@andrewebdev the `development` branch should be working. I just tested it and ran it both using `npm run dev` and `docker-compose up` and both are working for me. Maybe try and delete your .next directory and rebuild it to see if something is corrupted?

**Comment by andrewebdev** [comment]
@jupiter007 not sure why it's working for you because I just found the issue ;)

The import is for `typeaheadWithOther`- With an uppercase 'W', but the filename is with a lowercase 'w'. The import fails due to this. I'm not sure why it's working for you in this case. Maybe something cached.

Either way, I could add the fix to my branch if you want?

**Comment by jupiter007** [comment]
@andrewebdev that's very interesting. Not sure how it's working for me either :)

**Comment by jupiter007** [comment]
@andrewebdev glad you figured it out. You can also bring up questions to me directly in Slack if you are having issues with the app.

**Comment by jupiter007** [comment]
@andrewebdev feel free to fix bugs when you come across them in your branch.

**Comment by jupiter007** [comment]
> @jupiter007 not sure why it's working for you because I just found the issue ;)
> 
> The import is for `typeaheadWithOther`- With an uppercase 'W', but the filename is with a lowercase 'w'. The import fails due to this. I'm not sure why it's working for you in this case. Maybe something cached.
> 
> Either way, I could add the fix to my branch if you want?

Hi @andrewebdev I did some reading, and it could be that it was working for me because my file system on the mac is case insensitive.
