### ISSUE TITLE
Wireframe for Dashboard

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_frontend_prototype#77]

**Comment by fraserclark** [comment]
Link for Dashboard prototype

https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=886-782&t=ezIW5k9IdmCi0hHx-9&scaling=min-zoom&content-scaling=fixed&page-id=177%3A504&starting-point-node-id=886%3A782&show-proto-sidebar=1

This is a bit of a departure from phase 1, We went with a card-based dashboard instead of the table-style dashboard.


![Image](https://github.com/user-attachments/assets/2f86a43e-b819-43b3-9bc2-21791ad4939c)


There are a few reasons for this

- Data - We had problems trying to fit a lot of "data" in the table before, cards allow us to show more up-front data to the users without trying to squeeze it in columns. 
- Ease of use/smaller-screen-responsive - A card is more "collapsible" and flexible especially on smaller devices.
- Project-focused - As we have moved to a "project" approach, this means a researcher can have more than 1 DMPs - the card gives us some flexibility on displaying multiple DMPs
- The number of items - we know that most "normal users" doesn’t have too many active DMPs, so sacrificing some vertical space for more data feels worth it.

The nice thing about the cards is they are quite familiar to the rest of the user interface and mostly mirror the "edit project/plan" view 

There is a slight experimental "red dot" to suggest "action required", this is a bit of a discussion point/experiment of having some kind of action require indicator with text that exists on the card explaining the "action". so this might be "related works found", or "Accept invite to collaborate on this project" or something like this.

However, with all that said I did do an "alt" which is more "list-like" below the cards there is a little "Switch to alt view" - which would work like a collapsible panel - where a section of the information is in the "list item" and a panel can be expanded to show more detailed information, These would effectively became cards on smaller devices.

![Image](https://github.com/user-attachments/assets/71abd20a-b3c6-4974-9f8a-90c14f750786)

@briri @bofstein @andrewebdev @mariapraetzellis @PaulaReeves @jupiter007 @cazinc

**Comment by jupiter007** [comment]
Would it be possible to keep the cards, but allow for the collapsing of some info within the card if there is a lot of data? If most users don't have that many projects, then maybe it's ok not to collapse though. I was also thinking about a mobile scenario where the cards will stack, and then require lots of scrolling, so in that case, it might be nice to have the expand/collapse option.

**Comment by fraserclark** [comment]
Just wanted to expand on Juliet point around data density.

I think it would be better to try to make the hard decisions upfront, and trim the amount of data on display - if there are concerns on density.

It's tricky to expand/collapse cards generally because when it is in a grid, you end up with a weird grid where one item in a row has double the height of the rest of the row, never quite works.

**Comment by briri** [comment]
@bofstein is it ok to close these wireframe tickets #623, #624, #625

**Comment by bofstein** [comment]
Let's wait to close this until we decide on one of the two options, then when its closed we'll know which is our final wireframe.

I personally prefer the collapsible list view because I think it makes more sense as an ordered list personally; I don't think it needs to show a huge amount of information, as they're generally just looking for the one they want to open, so they need enough to identify it.  Two users so far also preferred it, will see what the next couple say.

**Comment by bofstein** [comment]
@briri as to your question on the 3 feedback tickets, I think we can close the Guidance one since we've made revisions after testing, but we should keep the other two open while we're processing user research testing for those flows.  I'll comment on each.
