### ISSUE TITLE
Create overall DMP Tool Header

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#89]
Should look the same as header on the current page. Likely need to fully rebuild this since it was a Rails template before.

![Image](https://github.com/user-attachments/assets/0a1f738e-e19b-4184-89aa-17cfc9ed9947)

Note that the Admin button is only for Admins

The drop-downs are currently hard to click on because a tiny bit of mouse movement outside the box makes it go away, something to improve in the new version
![Image](https://github.com/user-attachments/assets/250452dc-3dae-4e88-9201-1c8decfcbc25)

May need design input on dropdown, e.g. from Admin menu

**Comment by jupiter007** [comment]
Something to note is that this header and footer use "fontawesome" icon sets. Although I've copied the styles over in the "feature/add-header-and-footer" branch, I'll discuss with the developer team on Tuesday to see whether there's a point to putting the existing header and footer into the app, due to lots of style changes.
