### ISSUE TITLE
[Spike] Front end research and documentation

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#91]
Need to spend some time documenting the frontend app.

1) Update the README.md file in frontend app with more details on App, features, and project structure
2) Add some documentation to the repo's Wiki

**Comment by bofstein** [comment]
Document what we have for front end, libraries, where we will put new documentation (likely Github), talk to Terry perhaps

**Comment by jupiter007** [comment]
For now, I just updated the README.md file for the frontend app. As we go, we can start adding more detailed info to the Wiki page in the repo. 

I went ahead and put the update into PR review, since I think some of that info will be helpful to the team as we start doing more development work in the app.

**Comment by jupiter007** [comment]
I did start looking into mermaid.js yesterday, and may use it eventually in the Wiki page.

**Comment by andrewebdev** [comment]
I used mermaid.js **a lot** in the past and it's a wonderful library. It's great for rendering many kinds graphs on the front-end. The only issue would be to export those graphs to PDF later.

If the only use case is for the Web, then it's a wonderful choice, I absolutely loved my time with it.
