### ISSUE TITLE
Define URL structure for frontend

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#96]
For example:

template/tpl_2424 

template/tpl_2424/q/new 
template/tpl_2424/section/new

template/tpl_2424/section/sec_5a6a1
template/tpl_2424/q/q_a414f

**Comment by fraserclark** [comment]
My proposed would be something like this 

**Template builder**

template/{template id}
template/{template id}/q/new
template/{template id}/s/new
template/{template id}/preview
template/{template id}/s/{section id}
template/{template id}/q/{question id}
template/{template id}/q/{question id}/preview


**Projects/Plans**

projects/
projects/new
projects/{project id}

projects/{project id}/project
projects/{project id}/funding
projects/{project id}/collaborators
projects/{project id}/outputs
projects/{project id}/export

projects/{project id}/dmp/{dmp id}
projects/{project id}/dmp/{dmp id}/s/{section id}
projects/{project id}/dmp/{dmp id}/q/{question id}

I could see being in a question when editing a plan quite a long URL, but it is pretty hierarchical

If you are a purist, you might want it to be project/{id}/dmp/{dmpid}/s/{section id}/q/{qid} but that seems quite long to me but what is everyone else thoughts

**Comment by briri** [comment]
I think this makes sense @fraserclark. 

`project/{project id}/project` feels redundant. Maybe `project/{project id}/details` instead?

We will also want a `project/{project id}/related` or `project/{project id}/works` URL for the related works page (where the user can approve/reject works found by our harvesters.

I don't have a strong preference between the shorter `project/question` and the longer `project/section/question` format. I really like the use of 's' and 'q' instead of 'section' and 'question'. 

In the context of the Plans, would we have a separate URL for an individual question or are they navigating to a section which includes all of the questions on it?

Anyway, shorter is probably better. It will be less intimidating 😄

**Comment by fraserclark** [comment]
Yeah `project/{project id}/project` is dumb - agree lets make it details.

I thought everything should effectively be its own page, where possible.

So yeah, I think each question should be its own page. I think the benefits you get for "free" with it being its own page - like browser back buttons, linkable/shareable etc,

**Comment by jupiter007** [comment]
@fraserclark and @briri the urls look good to me. Fraser, in regards to your question about this url `project/{id}/dmp/{dmpid}/s/{section id}/q/{qid}`, it sounds like from your above conversation that `project/{project id}/dmp/{dmp id}/q/{question id}` can be used since questions will be on their own page. 

Will we be able to get the section info with just a question id from the backend if we need to?

**Comment by fraserclark** [comment]
Yep pretty sure. Based on @briri database structure cards, the questions are associated with a section - so I suspect GraphQL will make that easy to pull in that relationship

**Comment by jupiter007** [comment]
@briri, I am ok with those paths.
